### ISSUE TITLE
Make default tab following rather then hot.

### ISSUE THREAD

**Issue by tijno** [diamond-app/frontend#100]
Currently when user hits browse page without a saved "last tab" and no tab set in query string, it shows the hot feed.

This makes sense if user is not following anyone.

But right now even for users that follow people - it still defaults to hot feed.

Would it make sense to change this to following?

* Users are more likely to engage with posts in following
* Following tab is more likely to show fresh posts 

https://github.com/diamond-app/frontend/blob/1aed910a63513a863d91a7a16d2a8be55804ee5f/src/app/feed/feed.component.ts#L536

**Comment by superzordon** [comment]
Great feedback!

Closed via #114
