### ISSUE TITLE
BUG: FR set to 10% on Blog posting

### ISSUE THREAD

**Issue by tijno** [diamond-app/frontend#229]
See discussion here

https://diamondapp.com/posts/5783474d349bd789160b94c0af8a978173ff222cafa116c7b09a2904c07a026b

Cause this line:

https://github.com/diamond-app/frontend/blob/ea3a9a0d53a0c31c29af69a0dca7df28a3b519d3/src/app/create-long-post-page/create-long-post/create-long-post.component.ts#L274

**Comment by tijno** [comment]
@superzordon @jackson-dean

**Comment by arhebbar** [comment]
![image](https://user-images.githubusercontent.com/1827958/194710130-e02f0bab-76dd-4c5b-8214-3af837d28257.png)

Looks like that probably isn't the FR. It's Creator Basis Points. Also, I am not 100% sure, but I believe I did notice it happen on my profile and I went and checked FR of a few people at the time to confirm if the FR change happened and it hadn't. I am not 100% sure of this though.

**Comment by superzordon** [comment]
Thanks for the heads up - resolved by https://github.com/diamond-app/frontend/pull/230
