### ISSUE TITLE
Node fees result in incorrect notifications 

### ISSUE THREAD

**Issue by tijno** [diamond-app/frontend#24]
See example below - looks like they liked one of my posts, but these are fee payments.

This is because I have fees set on my node to come into my account.

![image](https://user-images.githubusercontent.com/69529928/137523408-3b13ec53-9643-4d84-8bae-9264afca2adc.png)

Fix may be to filter out, or show differently in this function 

https://github.com/diamond-app/frontend/blob/e7a539de18279571f98230dadcf0e29a572db3ef/src/app/notifications-page/notifications-list/notifications-list.component.ts#L97

**Comment by lazynina** [comment]
I think it would be better to resolve this issue on the backend. I don't think a user who receives DESO from a node fee should receive a notification.  [This PR](https://github.com/deso-protocol/backend/pull/207) should resolve the issue - let me know your thoughts there.

**Comment by tijno** [comment]
I can confirm latest backend update fixes this @lazynina so closing
