### ISSUE TITLE
Issue on displaying reaction details while someone repost X content

### ISSUE THREAD

**Issue by whoisanku** [diamond-app/frontend#301]
Here is the original post: 
![Original Post!](https://user-images.githubusercontent.com/85058931/217423575-ca8d9603-0f2b-4eaa-8032-105af18c3d65.png)

Here is the same post when someone repost it:
![No details when X reposted](https://user-images.githubusercontent.com/85058931/217423735-b97b5825-cb8a-4c38-83e9-afdc2dfa77a0.png)

Also, maybe notifications 🔔 has yet to be implemented!
cc @superzordon @stas-kh

**Comment by whoisanku** [comment]
After reviewing a bit, it seems like if X repost the content & someone react on that reposted content - then it displays out as taking reposted content as a separate one & displays reactions who react on top of reposted content! Not sure if it is just as it is or needs to be fixed. But yes, it is initial & tried to issue the findings.

**Comment by whoisanku** [comment]
Also there is an infinite loader for reaction when being in logged out state! 

![image](https://user-images.githubusercontent.com/85058931/218013117-eab334f5-35a2-48e2-b0ad-6d24cc63c74b.jpeg)

**Comment by whoisanku** [comment]
### Also would love to add another feature idea for reaction-modal as I can't do enough on Angular & Typescript so leaving it in my open issue!  
![All to fetch all reactions at one place](https://user-images.githubusercontent.com/85058931/218173044-fbc5c8d7-45ad-484a-b47b-8ba38df19283.png)

### It would be super cool if the reactions can be ordered by time duration but maybe there isn't any endpoint to support this.. as people like to see latest reactions to be prioritized at first which will make it in order

#### cc @lazynina :)

**Comment by whoisanku** [comment]
+ it seems like details of reactions from reposted content is shown in post container (as from your commit @lazynina ) but can't seem to see reaction details on reactions-modal while clicking from reactions when X reposted just like I've mentioned earlier 😀

**Comment by lazynina** [comment]
@whoisanku - yep, addressing in #307
